// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfOyssgvUgHJu7k4mi0c4Kf4uoAEbgxOk',
    appId: '1:827910058403:web:2ba63056a18d1d418a2a16',
    messagingSenderId: '827910058403',
    projectId: 'login-app-542c3',
    authDomain: 'login-app-542c3.firebaseapp.com',
    storageBucket: 'login-app-542c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDrn3H1lA-USQkyMMoZuxZ5xps91_UMss',
    appId: '1:827910058403:android:0d95142549f2d7658a2a16',
    messagingSenderId: '827910058403',
    projectId: 'login-app-542c3',
    storageBucket: 'login-app-542c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4pp6qd354Uxw9WkgROSzAOc--2cMKuEk',
    appId: '1:827910058403:ios:81ee48fca1aa530d8a2a16',
    messagingSenderId: '827910058403',
    projectId: 'login-app-542c3',
    storageBucket: 'login-app-542c3.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4pp6qd354Uxw9WkgROSzAOc--2cMKuEk',
    appId: '1:827910058403:ios:81ee48fca1aa530d8a2a16',
    messagingSenderId: '827910058403',
    projectId: 'login-app-542c3',
    storageBucket: 'login-app-542c3.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );
}
